# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "shipyard-power-connector"
client_id = "60cea657a300773ce6fcc42e8a742e23"
application_url = "https://bryan-press-sterling-corpus.trycloudflare.com"
embedded = true
handle = "shipyard-power-connector"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_orders,read_customers,write_merchant_managed_fulfillment_orders,read_merchant_managed_fulfillment_orders,write_inventory,read_inventory,write_shipping,read_shipping,write_assigned_fulfillment_orders,read_assigned_fulfillment_orders,read_fulfillments"

[access.admin]
direct_api_mode = "online"

[auth]
redirect_urls = [
  "https://bryan-press-sterling-corpus.trycloudflare.com/auth/callback",
  "https://bryan-press-sterling-corpus.trycloudflare.com/auth/shopify/callback",
  "https://bryan-press-sterling-corpus.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [
  "products/create",
  "products/update",
  "products/delete",
  "orders/create",
  "orders/updated",
  "orders/cancelled",
  "inventory_levels/update",
  "fulfillments/create",
  "fulfillments/update",
  "app/uninstalled"
]
  compliance_topics = [ "customers/redact", "customers/data_request", "shop/redact" ]
  uri = "/webhooks"

[pos]
embedded = false

[build]
dev_store_url = "databun-test.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
